all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: <Private_Key>
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
      - 44.204.35.48

kafka_broker:
  hosts:
      - 44.204.35.48
    
    
